# -*- coding: utf-8 -*-
"""activida1dmodulo3b

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fJIW7sKtal7Z8ykPpfXK7IU8M7x4shsz
"""

#importe de librerias
import numpy as np
import pandas as pd

matriz = ([['Mes', 'Gastos', 'Ventas'] , ["Enero", 20000, 30500] , ["Febrero", 18000, 40300] , ['Marzo', 25000, 82000] , ['Abril', 30000, 54000], 
           ['Mayo', 20000, 38000] , ['Junio', 17000, 50000]])
#matriz organizada con dataframe como una hoja de calculo

#colocar encabezaado a la matriz
encabezado = matriz.pop(0)
encabezado

df = pd.DataFrame(data=matriz, columns=encabezado)
df

# hago dos array para luego realizar operaciones matematicas
x = np.array([(1,2,3,4), (5,6,7,8), (9,10,11,12), (13,14,15,16)])
y = np.array([(4,3,2,1), (8,7,6,5), (12,11,10,0), (16,15,14,13)])
print(x)
print()
print(y)
print()
print(x + y)
print(x * y)
print(x - y)
print(x/y)
print()